title: Marabesi
email: matheus.marabesi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Trying to inspire people through software development. Here you will find posts
  related to web development and software engineering.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marabesi.com" # the base hostname & protocol for your site
twitter_username: MatheusMarabesi
github_username:  marabesi

paginate: 10
paginate_path: "/posts/page:num"

collections:
  pages:
    output: true
    permalink: /:path
  newbies:
    output: true
  projects:
    output: true
  tests:
    output: true
  conferences:
    output: true

markdown: kramdown

kramdown:
  syntax_highlighter: rouge

scholar:
  style: ieee-with-url

languages: ["en", "pt-br"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true
lang_from_path: true

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .travis.yml
  - node_modules
  - package.json
  - package-lock.json
  - .git
  - .vscode
  - .idea
  - .jekyll-metadata
  - .jekyll-cache
  - src
  - webpack.config.js
  - main-bundle.js

plugins:
  - jekyll-sitemap
  - jekyll/scholar
  - jekyll-figure
  - jekyll-redirect-from
  - jekyll-polyglot